rtconfig: mark RuntimeConfig Nullable in RuntimeConfigRefresher
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) null returned by binding at net.runelite.client.RuneLiteModule.provideRuntimeConfig()
 but the 1st parameter of net.runelite.client.RuntimeConfigRefresher.<init>(Unknown Source) is not @Nullable
  at net.runelite.client.RuneLiteModule.provideRuntimeConfig(Unknown Source)
  while locating net.runelite.client.RuntimeConfig
    for the 1st parameter of net.runelite.client.RuntimeConfigRefresher.<init>(Unknown Source)
  at net.runelite.client.RuneLiteModule.configure(RuneLiteModule.java:131)
  while locating net.runelite.client.RuntimeConfigRefresher

(cherry picked from commit 80f399e8e00ddae8c868d20e518b750d7e8a2a02)